#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor VGA-0 -d 0 1 2 3 4
bspc monitor HDMI-0 -d  5 6 7 8 9

bspc config border_width 1
bspc config window_gap 15
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config top_padding 23

bspc config active_border_color   "#5b5b5b"
bspc config normal_border_color   "#444444"
bspc config focused_border_color  "#7b6b6b"
bspc config presel_feedback_color "#e6d6ac"

bspc config split_ratio 0.6

bspc rule -a Screenkey manage=off

~/.fehbg
~/.config/polybar/launch
xrdb ~/.Xresources
